
import 'package:get/get.dart';

class MyTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'welcome': 'Welcome',
          'signup': 'Sign Up',
          'app_name': 'Elbet',
          'fitness_gym': 'Fitness Gym',
          'welcome_back': 'Welcome back,',
          'welcome_back_2': 'Welcome back!',
          'hello': 'HELLO',
          'hello_2': 'Hello,',
          'get_started': "Let's Get Started!",
          'create_account': 'Create an account to get all features',
          'register': 'Register',
          'back': 'Back!',
          'sign_in_msg': 'Hey! Good to see you again.',
          'sign_up_msg': 'We are happy to see you here!',
          'login_msg':
              'Enter your registered email id or contact number and password to login into your account.',
          'login_msg_2': 'Log into your existing account',
          'log_in': 'Log in',
          'log_in_2': 'Login',
          'log_in_3': 'LOGIN',
          'log_in_4': 'Log In',
          'log_in_5': 'Log In!',
          'sign_in': 'Sign in',
          'sign_in_2': 'Signin', 
          'sign_up': 'Sign up',
          'sign_up_2': 'Sign Up',
          'sign_up_3': 'Sign Up!',
          'sign_up_4': 'Signup',
          'sign': 'Sign',
          'up': 'up',
          'easy_sign_up': "It's easier to sign up now",
          'first_name': 'First Name',
          'user_name': 'Username',
          'user_name_2': 'USER NAME',
          'last_name': 'Last Name',
          'name': 'Name',
          'email_address': 'Email Address',
          'email': 'EMAIL',
          'email_2': 'Email',
          'password': 'Password',
          'password_2': 'PASSWORD',
          'confirm_password': 'Confirm Password',
          'username_hint_text': 'DavidLegend47',
          'password_hint_text': '********',
          'email_hint_text': 'example@gmail.com',
          'sign_me_in': 'Sign me in',
          'sign_me_up': 'Sign me up',
          'register_with_google': 'Register with Google',
          'google': 'Google',
          'sign_in_with_google': 'Sign in with Google',
          'sign_up_with_google': 'Sign up with Google',
          'continue_with_facebook': 'Continue with Facebook',
          'facebook': 'Facebook',
          'login_with_facebook': 'Login With Facebook',
          'use_email': "I'll use email or phone",
          'already_have_an_account': 'Already have an account? ',
          'forgot_password': 'Forgot Password?',
          'accept_terms': 'I accept the policy and terms',
          'accept_conditions': 'I agree with the Terms and Conditions',
          'remember_me': 'Remember me',
          'already_registered': 'Already Registered?',
          'dont_have_an_account': "Don't have an account? ",
          'need_help': 'Need Help?',
          'or': 'OR',
          'welcome1': 'Welcome to ELbet',
          'greeting': 'Hello User!',
          'choose_poetry_type': 'Choose the type of poetry you prefer,',
          'pop_or_classic': 'popular or classic?',
          'message_1': 'Welcome to Elbet \nusers',
          'Langue': 'English',
        
        },
        'fr_FR': {
          'welcome': 'Bienvenue',
          'signup': 'Inscription',
          'app_name': 'Elbet',
          'fitness_gym': 'Salle de sport',
          'welcome_back': 'Bienvenue de retour,',
          'welcome_back_2': 'Bienvenue de retour !',
          'hello': 'BONJOUR',
          'hello_2': 'Bonjour,',
          'get_started': 'Commençons !',
          'create_account': 'Créez un compte pour bénéficier de toutes les fonctionnalités',
          'register': "S'inscrire",
          'back': 'Retour !',
          'sign_in_msg': 'Salut ! Heureux de vous revoir.',
          'sign_up_msg': 'Nous sommes heureux de vous voir ici !',
          'login_msg':
              '''Saisissez votre identifiant e-mail enregistré ou votre numéro de contact et votre mot de passe pour vous connecter à votre compte.''',
          'login_msg_2': 'Connectez-vous à votre compte existant',
          'log_in': 'Connexion',
          'log_in_2': 'Se connecter',
          'log_in_3': 'CONNEXION',
          'log_in_4': 'Se connecter',
          'log_in_5': 'Se connecter !',
          'sign_in': 'Connexion',
          'sign_in_2': 'Se connecter',
          'sign_up': "S'inscrire",
          'sign_up_2': 'Inscription',
          'sign_up_3': 'Inscription !',
          'sign_up_4': 'Inscription',
          'sign': 'Inscription',
          'up': 'Inscription !',
          'easy_sign_up': "C'est plus facile de s'inscrire maintenant",
          'first_name': 'Prénom',
          'user_name': 'Nom d\'utilisateur',
          'user_name_2': 'NOM D\'UTILISATEUR',
          'last_name': 'Nom de famille',
          'name': 'Nom',
          'email_address': 'Adresse e-mail',
          'email': 'E-MAIL',
          'email_2': 'E-mail',
          'password': 'Mot de passe',
          'password_2': 'MOT DE PASSE',
          'confirm_password': 'Confirmer le mot de passe',
          'username_hint_text': 'DavidLegend47',
          'password_hint_text': '********',
          'email_hint_text': 'exemple@gmail.com',
          'sign_me_in': 'Connectez-moi',
          'sign_me_up': 'Inscrivez-moi',
          'register_with_google': 'S\'inscrire avec Google',
          'google': 'Google',
          'sign_in_with_google': 'Se connecter avec Google',
          'sign_up_with_google': 'S\'inscrire avec Google',
          'continue_with_facebook': 'Continuer avec Facebook',
          'facebook': 'Facebook',
          'login_with_facebook': 'Connexion avec Facebook',
          'use_email': 'J\'utiliserai l\'e-mail ',
          'already_have_an_account': 'Vous avez déjà un compte ? ',
          'forgot_password': 'Mot de passe oublié ?',
          'accept_terms': 'J\'accepte la politique et les conditions',
          'accept_conditions': 'J\'accepte les Conditions Générales',
          'remember_me': 'Se souvenir de moi',
          'already_registered': 'Déjà inscrit ?',
          'dont_have_an_account': 'Vous n\'avez pas de compte ? ',
          'need_help': 'Besoin d\'aide ?',
          'or': 'OU',
          'welcome1': 'Bienvenue dans ELbet',
          'greeting': 'Bonjour Utilisateur !',
          'choose_poetry_type': 'Choisissez le type de poésie que vous préférez,',
          'pop_or_classic': 'populaire ou classique?',
          'enter_poetry_type': 'Enter the type of poetry',
          'show_result': 'Afficher le Résultat',
          'message_1': 'Bienvenue dans Elbet \nusers',
          'Langue': 'Français',
        },
        'ar': {
          'welcome': 'مرحبًا',
          'signup': 'التسجيل',
          'app_name': 'Elbet',
          'fitness_gym': 'نادي اللياقة البدنية',
          'welcome_back': 'مرحبًا مرة أخرى،',
          'welcome_back_2': 'مرحبًا مرة أخرى!',
          'hello': 'مرحبًا',
          'hello_2': 'مرحبًا،',
          'get_started': 'لنبدأ!',
          'create_account': 'أنشئ حسابًا للحصول على جميع الميزات',
          'register': 'سجل',
          'back': 'عودة!',
          'sign_in_msg': 'مرحبًا! سعيد برؤيتك مرة أخرى.',
          'sign_up_msg': 'نحن سعداء برؤيتك هنا!',
          'login_msg':
              'أدخل بريدك الإلكتروني المسجل أو رقم الاتصال وكلمة المرور لتسجيل الدخول إلى حسابك.',
          'login_msg_2': 'تسجيل الدخول إلى حسابك الحالي',
          'log_in': 'تسجيل الدخول',
          'log_in_2': 'تسجيل الدخول',
          'log_in_3': 'تسجيل الدخول',
          'log_in_4': 'تسجيل الدخول',
          'log_in_5': 'تسجيل الدخول',
          'sign_in': 'تسجيل الدخول',
          'sign_in_2': 'تسجيل الدخول',
          'sign_up': 'التسجيل',
          'sign_up_2': 'التسجيل',
          'sign_up_3': 'التسجيل',
          'sign_up_4': 'التسجيل',
          'sign': 'التسجيل',
          'up': 'التسجيل',
          'easy_sign_up': 'من السهل الآن التسجيل',
          'first_name': 'الاسم الأول',
          'user_name': 'اسم المستخدم',
          'user_name_2': 'اسم المستخدم',
          'last_name': 'اسم العائلة',
          'name': 'الاسم',
          'email_address': 'عنوان البريد الإلكتروني',
          'email': 'البريد الإلكتروني',
          'email_2': 'البريد الإلكتروني',
          'password': 'كلمة المرور',
          'password_2': 'كلمة المرور',
          'confirm_password': 'تأكيد كلمة المرور',
          'username_hint_text': 'DavidLegend47',
          'password_hint_text': '********',
          'email_hint_text': 'example@gmail.com',
          'sign_me_in': 'سجلني دخول',
          'sign_me_up': 'سجلني',
          'register_with_google': 'سجل بحساب Google',
          'google': 'Google',
          'sign_in_with_google': 'تسجيل الدخول باستخدام Google',
          'sign_up_with_google': 'التسجيل باستخدام Google',
          'continue_with_facebook': 'تابع مع Facebook',
          'facebook': 'Facebook',
          'login_with_facebook': 'تسجيل الدخول باستخدام Facebook',
          'use_email': 'سأستخدم البريد الإلكتروني أو الهاتف',
          'already_have_an_account': 'هل لديك حساب بالفعل؟ ',
          'forgot_password': 'هل نسيت كلمة المرور؟',
          'accept_terms': 'أوافق على الشروط والأحكام',
          'accept_conditions': 'أوافق على الشروط والأحكام',
          'remember_me': 'تذكرني',
          'already_registered': 'مسجل بالفعل؟',
          'dont_have_an_account': 'ليس لديك حساب؟ ',
          'need_help': 'بحاجة إلى مساعدة؟',
          'or': 'أو',
          'welcome1': 'مرحبا في البت',
          'greeting': 'مرحبًا يا مستخدم!',
          'choose_poetry_type': 'اختر نوع الشعر الذي تفضله,',
          'pop_or_classic': 'شعبي أم كلاسيكي؟',
          'enter_poetry_type': 'أدخل نوع الشعر',
          'show_result': 'عرض النتيجة',
          'message_1': 'مرحبًا في البت \nالمستخدمين',
          'Langue': 'عربي',

        },
      };
}